site_name: "BeTFSM documentation"
site_author: "Erwin Aertbelien"
repo_url: "https://github.com/Robotics-Research-Group-KUL/betfsm"
edit_uri: edit/main/documentation/docs
copyright: "LGPL-3.0-only"
theme:
  name: "readthedocs"




nav:
  - "Documentation":
    - "Start page" : 'index.md'
    - "Installation" : "installation.md"      
    - "Tutorials":
      - "Introduction" : "tutorials.md"
      - "Defining your own BeTFSM node" : "tutorial_node.md"
      - "My first BeTFSM tree" : "tutorial_sequence1.md" 
      - "Defining state machines" : "tutorial_statemachine.md"
      - "Example with common nodes" : "tutorial_common_nodes.md"
      - "Handling interruption" : "interruption.md"
#      - "Up & Down": "upanddown.md"
#      - "Action servers": "actionserver_ex.md" 
      - "Executing and visualizing a BeTFSM tree" : "tutorial_gui.md"
      - "BeTFSM with ROS2 and Crospi" : "tutorial_gui_ros.md"
    - "Technical documentation" :
      - "Technical introduction" : "technical_intro.md"
      - "Overview of the API" : "api_overview.md"
      - "Event handling and conditions": "event.md"
      - "ROS2 Lifecycle" : "ros2lifecycle.md"
      - "Utilities" : 'utils.md'
      - "Logging" : "logger.md"
      - "Other references": "references.md"
    - "API" :
      - "BeTFSM":
        - "TickingState" : "tickingstate.md"
        - "TickingStateMachine" : "tickingstatemachine.md"
        - "Visitor" : "visitor.md"
        - "Generator" : "generator.md"
        - "Sequence" : "sequence.md"
        - "ConcurrentSequence" : "concurrentsequence.md"
        - "Fallback" : "fallback.md"
        - "ConcurrentFallback" : "concurrentfallback.md"
        - "Concurrent" : "concurrent.md"
        - "WaitFor" : 'waitfor.md'
        - "WaitForever" : 'waitforever.md'
        - "TimedWait" : 'timedwait.md'
        - "TimedRepeat" : "timedrepeat.md"
        - "While" : 'while.md'
        - "Repeat" : 'repeat.md'        
        - "Message" : "message.md"
        - "LogBlackboard" : 'logblackboard.md'
        - "Compute" : "compute.md"
        - "Adapt" : "adapt.md"
        - "Runner": "runner.md"
        # - "Ctrl_C_Receiver" : "ctrl_c_receiver.md"  # not useful for user
        - "AlwaysOutcome" : "alwaysoutcome.md"        
        - "EventOutcome" : "eventoutcome.md"
        - "EventConcurrent" : "eventconcurrent.md"
        - "EventSequential" : "eventsequential.md"        
        - "Not" : "notcondition.md"
        - "OrCondition" : "orcondition.md"
        - "AndCondition" : "andcondition.md"
        - "Callback_Condition" : "callbackcondition.md"
        - "Timeout_Condition" : "timeout_condition.md"
        - "HTTPEvent_Condition" : "httpevent_condition.md"
        - "Ctrl_C_Condition"  : "ctrl_c_condition.md"
      
      - "BeTFSM ROS2":  
        - "ServiceClient" : 'serviceclient.md'
        - "ActionClient" : 'actionclient_ros.md'
        - "LifeCycle" : 'lifecycle.md'
        - "TimedRepeat for ROS2" : timedrepeat_ros.md
        - "TimedWait for ROS2" : 'timedwait_ros2.md'
        - "Timeout" : "timeout.md"
        - "TopicEvent_Condition" : "topicevent_condition.md"
        # - "TopicEventReciever" : "topiceventreceiver.md"  # not useful for user
      - "BeTFSM cROSpi":
        - "load_task_list" : "load_task_list.md"
        - "SetTaskParameters" : "settaskparameters.md"
        - "ReadRobotSpecification" : "readrobotspecification.md"
        - "ReadTaskSpecification" : "readtaskspecification.md"
        - "eTaSLOutput" : "etasloutput.md"
        #- "eTaSLEvent"  : "etaslevent.md"
        #- "eTaSL_StateMachine" : "etasl_statemachine.md"
        - "CrospiTask" : "crospi_task.md"
        - "CrospiDeactivate" : "crospi_deactivate.md"
#    - "TODO": "todo.md"    
    - "About & Acknowledgements": 'about.md'




     
extra_css:
- css/mkdocstrings.css
- css/extra.css


markdown_extensions:
  - pymdownx.snippets:
      base_path: ".."
      check_paths: false

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

  - pymdownx.highlight
  - pymdownx.details
  - admonition
  - mkdocs_graphviz
  - pymdownx.arithmatex:
      generic: true


plugins:
  - search
  #- codeinclude:
  #    title_mode: none
  - mermaid2
  - mkdocstrings:
      handlers:
        python:
          paths: [../betfsm, ../betfsm_demos, ../betfsm_ros, ../betfsm_crospi,..]
          options: 
            show_source: false
            show_root_heading: true
            docstring_style: google



extra_javascript:
  - https://cdn.jsdelivr.net/gh/rod2ik/cdn@main/mkdocs/javascripts/mkdocs-graphviz.js
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML

#  - javascripts/mathjaxhelper.js
